name: Export 'gh-workflow.env'
description: "Exports to ENV all from gh-workflow.env file in current directory"

runs:
  using: 'composite'
  steps:
    - name: Export dot env
      shell: bash
      run: |
        if [ -f gh-workflow.env ]; then
            export $(grep -v '^#' gh-workflow.env | xargs)
        else
            echo "No 'gh-workflow.env' file. Nothing to export"
        fi
